apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin-api
  namespace: homarr
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: bitcoin
  template:
    metadata:
      labels:
        app: bitcoin
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: bitcoin-api
          image: ghcr.io/xfilipwozniakx/bitcoin_api:latest
          imagePullPolicy: IfNotPresent
          command: ["script"]

