apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin_api
  namespace: homarr
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: bitcoin
  template:
    metadata:
      labels:
        app: bitcoin
      containers:
        - name: bitcoin_api
          image: "ghcr.io/xfilipwozniakx/bitcoin_api:v0.1.2"
          imagePullPolicy: IfNotPresent
