apiVersion: v1
kind: Namespace
metadata:
  name: homarr-testing
---
apiVersion: v1
kind: Secret
metadata:
  name: db-encryption
  namespace: homarr-testing
data:
  db-encryption-key: ZDkyYmJiNDNiZjE5OTdlNmE4NTU0NzA3NmE3ZTI3YzhlMzkxMGE0NDlkOWVkNWIzOWU3MWU4NmRkNjJhZTIwMg==

