apiVersion: v1
data:
    nick: ENC[AES256_GCM,data:nwZ9YqQxHIrW19HS,iv:lZ18FXfay7l7ySLt3la9WvcH1JxMnjsekVMGodVTcpE=,tag:+6xdJOk8rj+FRpSlb9Lz4A==,type:str]
    password: ENC[AES256_GCM,data:QWOlffwCn8yr7TJr6Y9vbw==,iv:3rdsLRSMxBdv2ouVMmapUT9RgLraR6qD/3PLZmJHqZE=,tag:ScCsFif5ROb4Xu3JiTU+oQ==,type:str]
kind: Secret
metadata:
    name: test-secret
    namespace: homarr
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2V1U3TC9KTXVuWEpmb3E2
            Y2g2OTlOOXEyeUJQRHM4M3RVL21qUk1MUjBVCjRtNHNYZ3lXLzYweFhoL0E1OHlV
            Vi82SlJzbmdncnR3bmFsNzFFdU5SejAKLS0tIEdGY3c2NXExMXQ0WDExQTJISmc1
            MGFUQWpZMlFGUDFLWEJ0V3RNb0ZuVlUKyN1Ci6OOP7PVcwQANBjhhrpVZGMFvfLP
            LRAB2iW68Y8QHCt5ZpjYI/xj1KPh9owOMWmf8BA2MTksj1Vb7FI6EA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T17:38:30Z"
    mac: ENC[AES256_GCM,data:fpKPAMTtRi1F/jx3A8X+48E9tzC3hAuK/Cz9DeKv0iijxsztKLPaI69MByt09QHnNeVO1Y7AuNBl9/BTZsTg84jTCBPelyntlOPu4tB/tXQkP8Ss55hpl5Uty9yHIGs2PQuKtzxwxLunDHSlhRzdZhVTkLsnsDe0lvq/pLTajDY=,iv:l57T//JshnswRuIXoPCxDst44DVRyKt5Z8G/auZCToA=,tag:vk88Gxk4EM2ghCrWu1qXSg==,type:str]
    version: 3.13.3
