apiVersion: v1
data:
    API_KEY: ENC[AES256_GCM,data:yKZKRyMVQJADa0+dNGaf9D2OAbrkiP8bOCVM7JX1A3mr5MuAgDYLjHSv+aClOdnZgPuVrg==,iv:9XUIKwBZWHeadXYJANHBfQm+7Jd7ZdhuDgrWemUYPc0=,tag:uWdraV4jPqGxeSf9IWYO4g==,type:str]
    DNS_ADD: ENC[AES256_GCM,data:hNfaNTPoK5FQ81xoreWDZ3RXcEJL4Fg/qcCq+AVYlLhgVCDF2yQucrmUYPcvokYMnuclc7nT2to9QP2RQ3MOJw==,iv:3ZfNe3VgwhLfgMAcMpNBPxQH64v7my1/ZfiJGy4BqJ0=,tag:FWTQgW3W9TMLnf3mNphU4w==,type:str]
kind: Secret
metadata:
    name: api-btc
    namespace: homarr
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRXBMT0hsbVIvMXppSmdN
            Tm1mNTlPR3JlM3A5U1I4cnpOU3h5K2YyQWlvCkw4S3JUU1UwRG1EY21Bc0lHaUQ1
            bE5mdkY4ZVRaeHorOWVMUWl1dzcxMG8KLS0tIDRWU0tnOGp3OXdJSFM2SHpQa1Aw
            bkJEZ0JrQXd3MEMwRnhRK3pyTEtiaFUKuJr7PqYapLIuRPzcRjtj4yoXXrHd3u8C
            WwhQBjUc80gjy6g3JQLXaWx0WvFvxK/z6qJCzceQMm1FBinrHWFvBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T19:25:04Z"
    mac: ENC[AES256_GCM,data:RpqnQ1yyCXnVWjOaFChX5zQ71Pz0pwGz/3L0Am1yLWMxPskl2/3aXGTC0sLOvkWsS6s0LIkXXjJte46eF4CFfSDLM8I+UDxZhMAHN0I4nwTyftE+ZQLY5C55CGMRFkzPCa/pXAv1EDjE+aX6rEsnSj/M9TMnT/ZXNxUTOwRYofg=,iv:l7qinzj5aCZ06lcUH03f/6rqs+LrEorEaIJacZNaW9A=,tag:PYA00vzR6WneMNFzZGmVhg==,type:str]
    version: 3.13.3
