apiVersion: v1
data:
    API_KEY: ENC[AES256_GCM,data:tS4r9aNppHAHJiA6xewQM/TlEtOUqHd4UkMb27Wd7CAkfe5Q7fX5aB5RihYOoYk1YGFOqg==,iv:h1RRmoRWGx9VqlXlB17UvWiU91JFXI74Ww2Cfqo6bRU=,tag:M0CgdQlNpL9N5Bned9RWLw==,type:str]
    DNS_ADD: ENC[AES256_GCM,data:2rG+NUU6hyFQl7gx4JVflVxh5HOm5j/C+9rxbPvnqYweEzcMLfN6kaMEPMsa9e20GvdjV0Uxl5R7aoA8mRlmDw==,iv:h8UK7u68goNxCJy8rAcMMdwc73ENnjErbO+d9LZs2Dw=,tag:EHlLv4iD8ZOGaG/J++rneQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-08-24T19:04:31Z"
    labels:
        kustomize.toolkit.fluxcd.io/name: apps
        kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: api-btc
    namespace: homarr
    resourceVersion: "708708"
    uid: b635df9a-4fd7-4369-a94a-9c1b2c8d11fd
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOXpxQlBvSnR3cFFQdmhZ
            VGxBQTZGa2Ywa0xoc3VrOUIvT0lJQURoSDFVCk5jMmhIZ2VWM2JrVk9GQlJndFY3
            TzM0K3pscm5sVGJRN1F3K2s3ZndySm8KLS0tIG9ENXE3UW5iSU9ybDdjL2FPWjZV
            WTY1MUtiQVZjcnp1U3ZWbFFVeVlhZmMKNj87GL0t978WASwd9Q4j1LlqLnYok7D2
            72rql+PHg0IfWId1q0ZdA6CyBFQxG5+rL8XtHsiz8JGlo4RIhKMRcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T21:02:23Z"
    mac: ENC[AES256_GCM,data:FXcCgl/q5/rKXbBrxljlP0E/+TNhS4o/oesYsGycTWLKPXKjKQ260XjS33ftt9ZTm0bhFzyS8SXgtXP4NYGCeK6V9EHUPapq1mrXd4pUkzR/JSHvWtQr8oDg+N5ZbV/E/ZVNmgvoMzcO1MTktyQlQgmN5QElAZCesOQiGQY3dOM=,iv:JigNPbrWT+F26SYZchsvn/HtDvZX2iGJw3lvwmAYkdc=,tag:ra0q8JgXWCgCeTj5CITv0g==,type:str]
    version: 3.13.3
