apiVersion: v1
kind: ConfigMap
metadata:
  name: homarr-config
data:
  ENABLE_DOCKER: "false"
  ENABLE_KUBERNETES:    "false"
  AUTH_COOKIE_PREFIX:   "homarr"
  AUTH_LDAP_GROUP_CLASS:    "groupOfUniqueNames"
  AUTH_LDAP_GROUP_MEMBER_ATTRIBUTE:   "member"
  AUTH_LDAP_GROUP_MEMBER_USER_ATTRIBUTE:    "dn"
  AUTH_LDAP_SEARCH_SCOPE:    "base"
  AUTH_LDAP_USERNAME_ATTRIBUTE:   "uid"
  AUTH_LDAP_USER_MAIL_ATTRIBUTE:    "mail"
  AUTH_OIDC_AUTO_LOGIN:    "false"
  AUTH_OIDC_CLIENT_NAME:    "OIDC"
  AUTH_OIDC_GROUPS_ATTRIBUTE:    "groups"
  AUTH_OIDC_SCOPE_OVERWRITE:    "openid email profile groups"
  AUTH_PROVIDERS:    "credentials"
  AUTH_SESSION_EXPIRY_TIME:   "30d"
  ENABLE_DNS_CACHING:    "false"
  LOG_LEVEL:    "debug"
  NO_EXTERNAL_CONNECTION:    "false"
  TZ:    "Europe/Oslo"
  DB_MIGRATIONS_DISABLED:    "false"
  DB_DRIVER:    "better-sqlite3"
  DB_DIALECT:    "sqlite"
  DB_URL:    "/appdata/db.sqlite"

