apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  labels:
    type: local
  name: homarr-db
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1000Mi
  hostPath:
    path: /data/homarr-pv/
    type: "DirectoryOrCreate"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-pvc
  namespace: homarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1000Mi
  volumeName: homarr-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-pvc-new
  namespace: homarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1000Mi
  volumeName: homarr-pvc-2
