apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: homarr-ingress
spec:
  ingressClassName: traefik
  rules: 
    - host: homarr.filipwozniak.org 
      http:
        paths: 
          - backend: 
              service:
                name: homarr
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - homarr.filipwozniak.org
      secretName: homarr-tls-secret

