apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:H10RM4qsh1QyQ9HlKYLFkcX/FD8Wj3PB/6zyenJ5qFr7VCauknNZdPHl96g+OMZhqAx7Ep6OEWTAA5qim+/I2NiQLUOT0O725qLDiTRNbrBeMniBB4X1EA==,iv:CsM3MCtKUFNCIGr2u+79jDZJ3ap8Tx8V1ZpJhctIdSQ=,tag:7FppXN2WJRg0dKybIXEmWw==,type:str]
    admin-user: ENC[AES256_GCM,data:2R9RibcWSiYgf49qhwoEdWfX2pE=,iv:epp+rkHZg7cDQqcjPzyJsMucLwNCuFYLqvMAaqtB7tI=,tag:/eDSSrR+3284Lx8eJheTHw==,type:str]
kind: Secret
metadata:
    name: monit-sec
    namespace: monitoring
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T3VBZ25uMzNiYzJmTzhh
            UVVEUGJhSEp1QUt3c3hocW1Xai82Uk1kUzA4CkUzUm9XVUdyVjBYL1M3Vjh2c2Fh
            M3dnSi9pVGt0SDUwaWIyTlFBY1dGTFkKLS0tIGF0SnU2VmUvcWdia1Z1M2VOTmd2
            QXltVDkxMTVHcEpjUHRFUVoxNloxOGcKd3pJ9y64jCKzJyJ7S0JPnmx6WTi1lHVY
            xESwQwbxgSxQUgm+EukilmqHWa9lIwAq4aSBjtzqmZFw7LJmqFxVAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T17:24:18Z"
    mac: ENC[AES256_GCM,data:09aMghqTPmPpPZvIZZ7MiH9DIg+20N2VII+0XlMKje5PZYMJ1f2Cnc4N9QbqhlWYoCUKI6QGc3cSiscMt/OweW08X6kRlJ2g+v1LuT3aBAyyOm+jjqmhiERHJbXxY0DCC5PqmEhgcqFkSe10zOOyhElO5Ti3UDUi0o71mygsgcE=,iv:pkD/bJxNLt+NLNtflsbUPwupSHKO8cutCFUmmD7ryTc=,tag:uogZW+298hTJDcv0Rcv/yA==,type:str]
    version: 3.13.3
