apiVersion: v1
kind: Namespace
metadata:
    name: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZ0svbkowVnQzUHJ1QTBu
            NHZ1M3dKei94NW1Rck9LamNmaHE2TnhFakF3CisxSDI4SEJxRW9ZN3hyRzcxdTRF
            b05lQ2grMjdaTGtWSEpBUXBCYVR4TmMKLS0tIHZXRHNINzdhdmlKT1FwTjNmaG01
            TVVkR0tkdVk3dmVPMHBJRDUvTzJuSW8K73ZXyvUSnCvTjHixXUPm+C3EQW8wi29K
            uH2rAdOzWeBjCVepR/vYKjvtnhY8SlgYkCg4GJ8YEsszgGpcOxO4ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T06:41:39Z"
    mac: ENC[AES256_GCM,data:L4H8Rm7n9zrrQvNCse7DmbroFFcEOXQ6N2bIcrH0LRqc09tIx5bdzML4d4xpody95ts1xg7ZtTadvd0kLmcZQFnOtKgnnIkrWaXGn0qSlargxtk7Nzpdr0VYv/bTno0fmZu9BRVrEQ8wgFVAh58KJiF+PNjN6cnWuxNdqVNAasQ=,iv:tC/sD3UVGOV2+S1MdtiUrBmwCau0EWmYkjXrCGiI5xE=,tag:cnFpz3JMNi6eiG63DFg21Q==,type:str]
    version: 3.13.3
