grafana:
    enabled: true
    admin:
      existingSecret: monit-sec
      userKey: admin-user
      passwordKey: admin-password
    grafana.ini:
      security:
        allow_embedding: true
      server:
        root_url: "https://informations.filipwozniak.org"
      public_dashboards:
        enabled: true

nodeExporter:
  extraArgs:
    - collector.hwmon
