apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:un1SDMlcGs34ffBn+lAYvwOZ/G18fIhwifMZPFWBGY5NgnpRuzn6wCtfxjoZ2FuIPY0hJ1nyspE+z+CmX/eR8/IjoyL5UqnO,iv:H1VtqF51nXwYH+EhPII0m81wM2iuNmNozdYfqfemkRw=,tag:Rbw9Ddun06O74CZWcb07KA==,type:str]
kind: Secret
metadata:
    name: api-key
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2emFHSmRoaGkwRFNhMmlJ
            OTJTa3NpZStLUnk3MWd5M0I2NDZHTFpYUVVzCnlWd1d4NkZwTkZjbmcveExJcGtl
            cnhsQ2VkZmVnanRnTEU4MGtQamRhdlUKLS0tIGZ1WTNKRmZta014SThNNEdxODVa
            ZHdML3d6ZWJZZE80VFFCSWp3RjdGQ0EK62z739HyTq3yYjJq/v7zB4V17WXIbRws
            XsYqkpS2JDTuGzA6jPYdTfyG9xGZEmZqRMAE4Tt22r1Pr+WpKD5zjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T22:01:32Z"
    mac: ENC[AES256_GCM,data:Ye9oFBESc0Thcpcu/D2cMwvibk7ugfBCzwW+/S1AgJyhiS1Yk6e2ViZ7AcyK4c8j11f7w4vFhZSKaeA5R0MSEx0ZSUWHBAW3IuC9YwEOvloXq79e4cV/07N1iunMvb73tS23+q86huMH5Hl3O5HFGOhpv8FkP8bQuMDgICp6ruM=,iv:6RXOovPht0YC6XQTOAENrP+mYKFXaJfQmNkNDl0wVD8=,tag:sL2b/c1/a3oe2YlFwYMjkw==,type:str]
    version: 3.13.3
