apiVersion: v1
kind: Secret
metadata:
  name: db-encryption
  namespace: homarr-testing
data:
  db-encryption-key: YzE0MWIyM2UwNDBjMzg5YTRmYWFjMmJjMmFmYjM3MjRjMzIwNzEyMjE4YzVmNGViOTJlMzIzODA4NzhmNWE0Zg==
