apiVersion: v1
kind: ConfigMap
metadata:
    name: ntfy
data:
    #ENC[AES256_GCM,data:9OUoOEFnRSIcpu5kkhvAK0hamIKwynjr/+J1PQlDotDfle0sMaJFqOQchjpQ94WTv6WpP8Fxd5o+RmNGNSmu6E3tAxszB72N9uKHeg==,iv:XVVUZlzYDGxa2d0tN0b4XIL2HUJx3ech02snK/Qsk80=,tag:ke1aKm+OKEFjL4ggBGCRMA==,type:comment]
    server.yml: null
    base-url: ENC[AES256_GCM,data:HSQWM4Q5MGzxmGwsXOo8+y4RDPQYdy9g4o3ri5DuLYvaiZVC2m4=,iv:0Jgw4G7sIzsa2SvH1JlbgZPdWDmlesP2nWztA9Mosg0=,tag:9c1fJLY27wqMcxdnwyu62Q==,type:str]
    listen-http: ENC[AES256_GCM,data:517VzMU=,iv:ToelXnmjZHxl8c6VelZ2J/zfkjFbuZiDjrKa8JHBqBg=,tag:82UGcVd1ToYpD3WVrv+CZw==,type:str]
    behind-proxy: ENC[AES256_GCM,data:qEL5tA==,iv:Jj0doKKoQgiOrbGWWv4s3jt3cLTQGD4DDWUtCfgUbYM=,tag:AB9224NoRVU1O/92o8ZLcA==,type:str]
    require-login: ENC[AES256_GCM,data:Ur1FqA==,iv:OL8Bs4INouQNyrtMI6VbxdS/0beoIVmiaxcKpHMbVy8=,tag:JMg6sNoCum7qMvlaqUvQtw==,type:str]
    enable-login: ENC[AES256_GCM,data:b8sz5A==,iv:SkdSf+g3MKoBx6VyXptPPF0nEi5225Zcsg/hd4dmUt0=,tag:zI1aNumDIeFV9n+HCbG6ag==,type:str]
    auth-file: ENC[AES256_GCM,data:42rHo/dHR3cjiApKz9WKBRU=,iv:qUQGzJ8MCDO9qIT27Y61sT60Na84p0FXvZhdGVXKnaw=,tag:bEBReijiHSvrzri8BRc8Tw==,type:str]
    auth-default-access: ENC[AES256_GCM,data:M0DsD1PruZk=,iv:PPyu/2BjwMs5Ybg3hIF6JQgqDcyDXKMZIDM3a1eNRgM=,tag:pOR/Bhk3bl/I1Um1u5Z+LA==,type:str]
    auth-users:
        - ENC[AES256_GCM,data:Hi1M9tJ2CF64PVTipVNuetfdNl1x+ecISnGVuv0OLOGABwcpHEnxhNYhYUsxeMotalBEg5PimG+HUpxVRQKIpgmKUXO/foxQaQ==,iv:dcc+OaDweUGNgXGhFe0jpcYW0fXOEqDA4jIqKEjF4uk=,tag:3/MEvOQE5gkymfQV1oM3iQ==,type:str]
        - ENC[AES256_GCM,data:CuLzL3xdPKEPLKZ8tVH7LmZcINZuzrzXqoYbjO4IIrFxK2nJI0GAgD93OsxNM9GgV5CWfkeikpleSZohBR6881Oaw9AkwmI0SQ==,iv:aqPRSG5gS0jrK4Wavd52EifJU6kddXSiWKNdpHiL6s0=,tag:gTNZzTd20IYY7lIVjPYSOg==,type:str]
        - ENC[AES256_GCM,data:zmV78iendwJUMJr+zkk5FRrI/aChv1jORlX3IZuAu6nTXrTsYNJ8xB2fgl4wNMdX77qblGAOsaT54/EMUa8zdy0omWOfkE02rw==,iv:E4/MxdzxSa3cJjY4D2e1DyGyXnyo0j/h5X2pfEnrULw=,tag:+SciCsFk7bS+jSLKq1wkbQ==,type:str]
    auth-access:
        - ENC[AES256_GCM,data:KKkOvKz4EibZK0AOJR5LTpVovnF4,iv:s7vi4WmhxV6t50jKT5UxwWLXLejsraTWvusbaKOp270=,tag:JVEQDtxIZs+dm6PTT3dTvA==,type:str]
        - ENC[AES256_GCM,data:XTU2RRbteARsF0yBgAzfJ5KYI3nRGhLOdOo=,iv:ZWw1vlhugDH65YRr+8gbl2Ua/rUOt0xL2uFiPqp74/o=,tag:zkQYOucvRzAc2EL3fl6hbw==,type:str]
    auth-tokens:
        - ENC[AES256_GCM,data:qNImRAh/yP6g6hyViCXN0EAt0g6kswj1DHGntWkVCQyFLLQtXWG4ZYQshyR7btyvLayV,iv:cbNXxeIWcbSrmb/bFfNlKRiGWitVU8rLfWLXR0p2vzU=,tag:26YroAzBrQGDTQwTrw0b3w==,type:str]
        - ENC[AES256_GCM,data:DsMZO/T+/lVaKCGhrorh/7U9jyHRUwj2hbKP8+Lp89K0ToN//pjAFRmvDnMpA630cpqj,iv:Hg7l/EYmIfVxhKyoYrqdXlmt0fP3R5XQTxfbYNIzAM4=,tag:TnpASJbYYKAH5X4RNpFuMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSVRNekdKYSsveUtkTjMr
            VUh1TTJvc3FUWFUzQ2JWeGlxMWZsb0ZoV2pNCjE1R1QzNnJIeHQ4bGhOYUh0K1dC
            RG5VSTFucFhOVDV3QWhkMEVBNExoUncKLS0tIDlJK3dJeVZ5SnNRVHpBVEFrdlJp
            T1Ywa1c0alZOUHJXZk5sNjNTT1RiV2cKHWtvY65Uaj/cDuJW1KxC1780eTrQbypS
            jVdJzk+Epd6mEAqKDKkY1rAcjnzRA6lsrDY1z6Giv5vViI/+pxidyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T14:19:50Z"
    mac: ENC[AES256_GCM,data:u/4kg9ji1BpHyl4F/E/tf0okj3/KbIiKh/tFEulLwJnYi5Kw/VF2215Ij5CqQvFMFYYAMfqEflezTDUZ2DmwhhDakS5Y4YHlBsl7cN5JFDpiorY6m7dyyaN+sif0nbm8OcUYWp25+ac/WzincyUwE+tR+4uumDjd7QIBPfjzgwQ=,iv:K3ga2Hh63XespPBNmnRnyrFAQP2km6HsDibasfaflrI=,tag:Hmi2iFa43eOoTjAsiVRBCQ==,type:str]
    version: 3.13.3
