apiVersion: v1
kind: ConfigMap
metadata:
    name: ntfy
data:
    #ENC[AES256_GCM,data:g5K9fwWVWhLhK82ZQ+xZLKhYhepcue7JfaQZjp2yRCNW83eMwUVReD11xH7XtAYiPCHszHfId5Gnh7aFF4ZjFL3P3mvRrDKK5XQJXw==,iv:eo3kBObQ5gL0eYhrtZ5KELCuv93p9J4kaGSj3H1QhZA=,tag:VBLsnYtfdoHPbX/Gzt8czA==,type:comment]
    server.yml: null
    base-url: ENC[AES256_GCM,data:N2O7BVt2VR1cYgk0mAYGQcKszys+EET0Q5CHe9Jz8bSrEPmKHfU=,iv:I4mz2vRnFxEKYElX/QC4GtC8XT0WDJHeJCHHq9V0+HU=,tag:gjb0TTtF8XpKwuGOwR5hMA==,type:str]
    listen-http: ENC[AES256_GCM,data:I4jJq1k=,iv:LPq0H13/KPT9QI5sEB19BfRRNNo3aMY7U/xjHvVfgss=,tag:nh8gp2OFO+IpgffRrVmOSA==,type:str]
    behind-proxy: ENC[AES256_GCM,data:naE1Dw==,iv:QB5yWHqAwOJ8UL/mg3+C36Qi0DCy2RrDMKXvW9xgR78=,tag:uvcILpk3KiIz0e6X+/m6gg==,type:str]
    require-login: ENC[AES256_GCM,data:pKQZIQ==,iv:EMMTtopViQiq7eu/mEzN0ytJMIUovLvpimfmoFvNJas=,tag:2bi8TawAQ5vAFko4iYoR5g==,type:str]
    enable-login: ENC[AES256_GCM,data:V5GmOw==,iv:sBwJrU0EoOfSQHhDnJNcEQcIOCaCQvZfdTl3hJmk4pA=,tag:LcKh2Rpe4jNY0ah8S1LVtQ==,type:str]
    auth-file: ENC[AES256_GCM,data:XKO+fgaf2XFLvdT+swLUMPM=,iv:abMoOdo+YVV4/k2l1+KZGP+048AwMGB/NXVNOWQpFhc=,tag:++mPbt6mv3Ow0AuGcXMirA==,type:str]
    auth-default-access: ENC[AES256_GCM,data:+Xe3vzjDL9M=,iv:I1crEYs9JdAe7D2qh9QvAO0vu2rLrA+fw7fzlw3dOpM=,tag:q7N5LFNq5DmcyoR4TQenHg==,type:str]
    auth-users:
        - ENC[AES256_GCM,data:FsYSo6+RNeP4FW3f5zfcRmHgPPTmvV7LkB5CG0D7/a3fxBfP9ue+eFALG9qNlK9K7tXG4BZpKBrnfND3M33/C4gIEC40tUdi6g==,iv:eJPEiFG0DoAtwuzjyNZvrmBH9RsfIbOpRVBb1aoIKy8=,tag:mrqBzkNNIzZSHzkKkV3H0Q==,type:str]
        - ENC[AES256_GCM,data:kJl02k6tVyW8nYbgmKvB53/oiDmkc48antT3jWvJ0uBZHIrMx4spHqxqk30IlkxSIWy+SFWLCtM1TKwBeg8C6c6pUExikCyukg==,iv:FaUx9XaWC0PquxtAzgRO+18ImChtvZIHU5M7HOq29oI=,tag:NonUqUBIomoCZanyu9uJCA==,type:str]
        - ENC[AES256_GCM,data:ZwltZeX78yMqAOD6coqouMX2CbJPHvpUUCkZG3w9iMFxzW05Qi6wWOxq71VAv+DmQZRBJ+oAjX7vNcv8zev9cF8/uqiU/RtyZA==,iv:6JE472KwrovsVX3/a4Z+ZxA6Dl4iwyzarilGwFZ/Wsk=,tag:tY5umN8Jd083a1VUYdNBIQ==,type:str]
    auth-access:
        - ENC[AES256_GCM,data:gaKUfpXRsB54wVzv8W9IL21RiNOq,iv:QODt/7JzGMiaE4a2c2kS7GiSu0L0g3Y+5m5m14ALwTE=,tag:8h9dmLV2l6G18EZjbW/RRw==,type:str]
        - ENC[AES256_GCM,data:ri3hisWgYk1t1dF6fROswXy74e3Fu9rMg9U=,iv:kUtJk7ti3q3eC0Ju8hgwq0gXwGlWt2XQ/c8eGJAb7yc=,tag:tCPzllqbU1ziXqVAx0yWfA==,type:str]
    auth-tokens:
        - ENC[AES256_GCM,data:NPjOzKy46KHArYhKECegJ6ZO8g25gjhK18qm4LdfiQlPDV6LKGIH8/1VWsbl0WDFLC45,iv:/eAA1DoNLZ8Gq7nIeLqBJcM6Xiaa4UNrzVmG3mgIIvI=,tag:Umbof1lpeoDyNGpTdecrsg==,type:str]
        - ENC[AES256_GCM,data:Gmj0dz55BEcmiyGxdKKLCN/V2gxb+2U/ivS7s45uiaKpxsQ3Gt6FsoI7oD7UyyLeeKNz,iv:sbxcHLNKvY89KfwPLh0kYFSNST1vYmJxLp8DXZ1cu1k=,tag:YZMSitl7MJ+a7yS6s3Z52A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVVV1TGJPY0JuMDMrSDVN
            TzkweTRnY1pESG85RER1YlA5Sy81dWVtVERrCitjckxIMzI2T3hhY1lYMFlsVVE3
            aXMzSDJqMi9zNjlxWFo3bmFiR24xYVEKLS0tIDQxR1dZMEVaSVNPZTZGTE0yaStT
            RGNWd0tMbGNDTS95aXlNT0VmWnJtSFUKj9rStnoo2+65O/MckbymFbFw0KzuZDnz
            tcasp9m/Po4Z2I488jsKHd8hBnz1HLoe92P8C5nrR5mA+ycoKWwjuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T14:29:11Z"
    mac: ENC[AES256_GCM,data:X/spyo8UueYGYnuOu9AkPF7h/L1d6zAkILK9YzBe3o4KKd3nv2fhR/oQH8Hp/v4Qgp8r/hJR14jROwI6NoS0OUHRaE5sqxO60DvcY6ZbH+33ic33LSK3VlNYwJT3E4/AHAz5n4jhhT+jLdLzCxe9Q+qm+ybGzYkvZC6uHSUrQ5c=,iv:gEoTfhD0I3yIjPiGF2F6TN532O1XUHHHaCLae8q2bIg=,tag:quAU3e50E0wHjnxK8mfqMQ==,type:str]
    version: 3.13.3
