apiVersion: v1
kind: PersistentVolume
metadata:
  name: ntfy-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1000Mi
  hostPath:
    path: /data/ntfy-data/
    type: "DirectoryOrCreate"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1000Mi
  volumeName: ntfy-data
