apiVersion: v1
kind: Service
metadata:
  name: ntfy-srv
spec:
  ipFamilyPolicy: SingleStack
  type: ClusterIP
  selector:
    app: ntfy
  ports:
  - port: 9999
    name: main-port
    targetPort: 9999
