apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: filipwu95@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: certificates-dns01-prod
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: api-token-cloudflare
            key: api-key

