apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobook-deplo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audioshell
  # strategy: 
  #   type: RollingUpdate
  #
  template:
    metadata:
      labels:
        app: audioshell
    spec:
      containers:
        - name: audiobook
          image: advplyr/audiobookshelf:latest
          imagePullPolicy: Always
          ports:
            - name: main
              containerPort: 13378
              protocol: TCP
          # env:
          #   - name: j

          volumeMounts:
            - name: config
              mountPath: /config
            - name: metadata
              mountPath: /metadata
            - name: podcasts
              mountPath: podcasts
            - name: audiobooks
              mountPath: audiobooks
         #################
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
        - name: metadata
          persistentVolumeClaim:
            claimName: metadata-pvc
        - name: podcasts
          persistentVolumeClaim:
            claimName: podcasts-pvc
        - name: audiobooks
          persistentVolumeClaim:
            claimName: audiobooks-pvc

