apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: podcasts-pvc
spec:
  storageClassName: "local-path"
  accessModes: 
    - ReadWriteOnce
  resources:
      requests:
        storage: 5Gi
  volumeName: podc-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: audiobooks-pvc
spec:
  storageClassName: "local-path"
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: audio-pvc
