apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: podcasts-pvc
spec:
  storageClassName: "local-path"
  accessModes: 
    - ReadWriteOnce
  resources:
      requests:
        storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: audiobooks-pvc
spec:
  storageClassName: "local-path"
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: config-pvc
spec:
  storageClassName: "local-path"
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: metadata-pvc
spec:
  storageClassName: "local-path"
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
