apiVersion: v1
kind: Secret
metadata:
    name: api-btc
data:
    API_KEY: ENC[AES256_GCM,data:Cx1CmP5iRTvuj3m71Vm6NY1bFiVDSJkCMXU3nzUJy1u8tBqCTnXZIXD6bi9XC0ExCrxXnw==,iv:J1yJaob+xQiZaHoODasCj2+ingWy9twVOBMw1w5Bacw=,tag:qyCqvkmEiRvXeyJyJh6S9w==,type:str]
    DNS_ADD: ENC[AES256_GCM,data:EP/CGnjbyTNIyoUNKJ/ZdDyf85aWyHvDmnA6C7i6LkoxBkq6jjxz5omyPD/LIm/SKv09iV2jYc6rXFl8TU80PQ==,iv:wggwvA22LZ7ljQ+K96WlHvpROKcB1xaS9tTHcvrZ2kU=,tag:Zb8KZ1qdEzmn+6bNkr6zPg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WXBWQU9MaE1rUm5RK0s3
            M0QvSHk5aVl4TGNDdlVkMjAza0QzNU5VOUJRCmZrWGZ2cjlNVm1uRDBhSXNpcXNh
            SURiOGpuY2tJREpPZFNuOE8wbHI5UnMKLS0tIDJDR2RkeGdXR2pIOTJCTjZOZ3Bn
            S05EaFZFUVpvemt3RjA3TFZSaDlOeEkKUNQ3/KnWcvCM3FAshH1jjYpG883v0vCL
            V4tLEvhiwT6FWy0gK0NNGFHzPWeq0Q/Hq4mKf+DyXDOEtXhrASwqjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T19:34:37Z"
    mac: ENC[AES256_GCM,data:TzQCxbVtx1lwdetL6JIA1BGax1e/jFcnOiOmFB3AY4n+YZnTXCG9e3u9i0qxMQMn+CsFN39WwPhfQPBYfXvLRneH2taFWFNeJXp5ya1+Kaqmho12a2QU/BdmKplbq8HbJknUuph0ZxIyb7XUlSXQEYg0xUu0QcF/qNRcb3DsI1s=,iv:nPs4918Cb2nETxN7oMUjfJ65/u4+qk+PyfGFAUqFqoc=,tag:qrwzHvsREaUi9xyrF82vRA==,type:str]
    version: 3.13.3
