apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: ingress-nginx
  cert-manager.io/cluster-issuer: letsencrypt-prod
  traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec: 
  ingressClassName: traefik
  rules: 
    - host: bitcoin-api.filipwozniak.org 
      http:
        paths: 
          - backend: 
              service:
                name: btc-api-svc
                port:
                  number: 8082
            path: / 
            pathType: Prefix
  tls:
    - hosts:
      - bitcoin-api.filipwozniak.org
      secretName: bitcoin-tls-prod-secret

