apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
data:
  server.yml: |
    # Template: https://github.com/binwiederhier/ntfy/blob/main/server/server.yml
    base-url: https://notifications.filipwozniak.org
    listen-http: ":9999"

    # Various feature flags used to control the web app, and API access, mainly around user and
    # account management.
    #
    # - enable-signup allows users to sign up via the web app, or API
    # - enable-login allows users to log in via the web app, or API
    # - require-login redirects users to the login page if they are not logged in (disallows web app access without login)
    # - enable-reservations allows users to reserve topics (if their tier allows it)
    #
    # enable-signup: false
    require-login: true
    enable-login: true
    # enable-reservations: false
  
