apiVersion: v1
kind: ConfigMap
metadata:
    name: ntfy
data:
    server.yml: | 
      # Template: https://github.com/binwiederhier/ntfy/blob/main/server/server.yml
      base-url: "https://notifications.filipwozniak.org"
      listen-http: ":9999"

      require-login: "true"
      enable-login: "true"
      auth-file: "/datebase/user.db"
      auth-default-access: "deny-all"
      auth-users:
        - "server:$6$FLxmHTyxDSZZUtyo$Oj0XbudEq3.U36sEp.DpcnXOhQFdbg7HCd7XoMA14LxD8GaXiBGbQInaBVSez8c4Vcna5pejM4nqaLV3ArWoL/:admin"
        - "pi:$6$rJzheKCXvHYOKzxq$h2AWTU2ZedBlyJnpBlMjmeEjbiLE3z8lL721Te0.zIp2nt33JBjMcUMLwRCWBHaTmzvwTmGRbZH6McdWg98JX.:/user"
      auth-access:
        - "admin:*:rw"
      # enable-reservations: false
