apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: filipwu95@gmail.com
    profile: tlsserver
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: certificates-dns01
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: api-key-cloudflare.yaml
            key: api-key


