apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
spec:
  interval: 1m
  type: oci
  url: oci://quay.io/jetstack/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 1m
  chart:
    spec:
      chart: cert-manager
      version: '1.21.x'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 1m
  releaseName: cert-manager
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    crds:
      enabled: true

