apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobook-deplo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audioshell
  template:
    metadata:
      labels:
        app: audioshell
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
      containers:
        - name: audiobook
          image: advplyr/audiobookshelf:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 1000
            runAsUser: 1000
          ports:
            - name: main
              containerPort: 3005
              protocol: TCP
          envFrom:
            - configMapRef:
                name: audiobook-config

          volumeMounts:
            - name: config
              mountPath: /config
            - name: metadata
              mountPath: /metadata
            - name: podcasts
              mountPath: podcasts
            - name: audiobooks
              mountPath: audiobooks
         #################
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
        - name: metadata
          persistentVolumeClaim:
            claimName: metadata-pvc
        - name: podcasts
          persistentVolumeClaim:
            claimName: podcasts-pvc
        - name: audiobooks
          persistentVolumeClaim:
            claimName: audiobooks-pvc

