apiVersion: v1
kind: Service
metadata:
  name: ld-loadbalancer
  labels:
    app: linkding
spec:
  ports:
    - port: 9090
      targetPort: 9090 # targetport is port that inside of pod
  selector:
    app: linkding
  type: LoadBalancer
