# better option gensha nfs 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-srv
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nfs
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
        - name: nfs-srv
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
                - SETPCAP
          image: erichough/nfs-server:2.2.1
          ports:
            - name: nfs-4-tcp
              containerPort: 2049
              protocol: TCP
            - name: nfs-4-udp
              containerPort: 2049
              protocol: UDP
          volumeMounts:
            - name: media
            #  mountPropagation: HostToContainer   # might cause issues
            #  readOnly: true                      # might cause issues
              mountPath: /shares/media
            - name: logs
              mountPath: /shares/logs
 
          env:
            - name: NFS_EXPORT_0
              value: "/shares 10.0.0.15(ro,async,no_subtree_check,all_squash,anonuid=10001,anongid=10001,fsid=0)"
            - name: NFS_EXPORT_1
              value: "/shares/logs 10.0.0.15(rw,async,no_subtree_check,all_squash,anonuid=10001,anongid=10001)"
            - name: NFS_EXPORT_2
              value: "/shares/media 10.0.0.15(rw,async,no_subtree_check,all_squash,anonuid=10001,anongid=10001)"

      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-blog
        - name: logs
          persistentVolumeClaim:
            claimName: logs-blog
