apiVersion: v1
kind: Service
metadata:
  name: nfs-service
spec:
  ports:
  - name: "nfs-v4"
    port: 2049
    protocol: TCP
    targetPort: 2049
  selector:
    app: nfs
  type: LoadBalancer
  externalTrafficPolicy: Local
