apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: linkding
spec: 
  ingressClassName: traefik
  rules: 
    - host: linkding.filipwozniak.org 
      http:
        paths: 
          - backend: 
              service:
                name: linkding-service
                port:
                  numer: 9090
            path: / 
            pathType: Prefix
