apiVersion: v1
stringData:
    admin: ENC[AES256_GCM,data:A1Z4rp0UUPwf,iv:4xFVgIJBVjFsujxo7nNmlgn4rggWEBirJP2MEWgF1Po=,tag:8ydKyiRiks+lpYeqTiOXXQ==,type:str]
    pass: ENC[AES256_GCM,data:7MDR+Eh3uiPYaFv4nF52Y4TK6fs=,iv:rXhvXTJNFggXca6GBvNeRlmVXyCzvIn7aNLfITF0GH8=,tag:afZ/5qrsfhKURY/LsQg5+g==,type:str]
kind: Secret
metadata:
    name: creds
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZFhEVHdiZC9kbTZhNE9s
            WWhwbWFhRmhHeFJ3czB1T1lDd1V1eGhENWk4CmJpOHVSSldVL1BmTGMzaHhML1Yy
            N3ZlKzE1L2djeXc3M0JUQzF3Ly9sMFEKLS0tIEZiWG00cmREdnBGRFFscUlWQXU2
            dzRNTkxvcjkvb0NoSE0xUXBhOG82MU0KS1kL0ly5DmzvK1nRUtXW2PwRJXMZJ33X
            BDQhqlX8gZdx3STZlgMkr1yiVvD/wLJWuOB75i4CwzwiAd/OTg/1rg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T08:32:35Z"
    mac: ENC[AES256_GCM,data:bxItusSXXSffF1DOXm8fOQM9S/nbBQlh1uERlWixhZBxikB5vWLM+9Vwq/H+p50XDFgN0a1QZ5klalD7JGPMcVXSqFzpdTcB2tU8KqTYrZePm2xJgL4h7LqgsNyr0/ZM4w/7XGtqVxCx2ue0jE2WQOrr6OiNaOK3B7j0pkcjEX4=,iv:R7rgJydL1Tj1rQcP9L5guIoNEiWbrjJzCyhOAIWiP+k=,tag:XMlmufTccUH4Vj6dSackUA==,type:str]
    version: 3.13.3
