apiVersion: v1
kind: ConfigMap
metadata:
  name: proftpd-config
data:
  FTP_DEBUG_LEVEL: "8" # 0-10 (10 = most verbose)
  FTP_LOG_LEVEL: "info" # debug, info, warn, error
#  FTP_MASQUERADE_ADDRESS: "${FTP_SERVER}"
  FTP_PASSIVE_PORT_RANGE_START: "60000"
  FTP_PASSIVE_PORT_RANGE_END: "60004"
  FTP_SQL_USERS_TABLE: "users"
#  FTP_TLS_CERTIFICATE_FILE: "/etc/letsencrypt/live/${FTP_SERVER}/fullchain.pem"
#  FTP_TLS_CERTIFICATE_KEY_FILE: "/etc/letsencrypt/live/${FTP_SERVER}/privkey.pem"
  FTP_TLS_REQUIRED: "on"
  FTP_TLS_WAIT_FOR_CERTIFICATE: "true"
  MYSQL_DATABASE: "ftpdb"
  MYSQL_HOST: "mysql"
  MYSQL_PASSWORD: "testing_functionality"
  MYSQL_PORT: "3306"
