apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: proftpd
resources:
  # - configmap.yaml
  # - deployment.yaml
  # - namespace.yaml
  # - pvc.yaml
  # - secrets.yaml
  # - service.yaml
