apiVersion: v1
kind: Service
metadata:
  name: proftd-service
spec:
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  ports:
    - name: ftp
      port: 21
      protocol: TCP
      targetPort: 21
    - name: sftp
      port: 990
      protocol: TCP
      targetPort: 990
    # - name: passive-port1
    #   port: 60000
    #   protocol: TCP
    #   targetPort: 60000
    #
  selector:
    app: proftpd
    

