apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:nNxBiJglHGoiJ7L0ofxwpxJBhpJt4V46Dlt/nX1aUDlExZ0m7R9ngulgrWjBNXEP21qdJuehlF4=,iv:/jbsOXG0spwKqy8zYmVo6RLhOM+iXpU/wMt/k6hRFVM=,tag:y0JyNA/12X4cx5fp9Pq0Sw==,type:str]
kind: Secret
metadata:
    name: renovate-secret
    namespace: renovate
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRDNNbDhXQ0F1SmVFd1ZO
            YVlhcGVaQUJJanVsdTcvQml4OFNWc2pDK3lVClovbVNnYTdLRS9PRGZiOVVUQktL
            cWJzQVJTeDZ6OFVuSHZlTnpjRGhuN0UKLS0tIDEzalN1R2ExbVpROGV4dWs4ZXoz
            ZVczSWVBeWxFM2pJRkdnczNaVkdkTUkKucMvCy5z6rMho9fLG143K9KSfFIzzWfi
            tBS7WvbBX9y6lAXf3jbbRQ4CmMXXA0F9ZuRWX9TAaMEehJ3f1gX65w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(RENOVATE_TOKEN)$
    lastmodified: "2026-08-27T09:43:20Z"
    mac: ENC[AES256_GCM,data:+BRaUB8OXr/DjQsIEmbxBvf9sn5YHxXRvzA4202bUSRYNmmj3SKCWFJ71eVHvEy4c2SrJaSdhRO2LttBbx1mkKbpTcgcd9H3BdHFkn8HTbVP6DyNIqPmmNGRv5TYaUONrs/GLuwjbvGDsuONvOUTxUl7Du3yospqOTXgYdkUphA=,iv:LuR6F6kiJfwEm+N6wijqdsQDN8dDzFTnfa8NiU8HTzQ=,tag:yjgoiWFS3qXW9HKqQqtKZQ==,type:str]
    version: 3.13.3
