apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:WaTHvHp6QmySw5HPoX6quf8XK0lenu4/NFaV3bxZkT9M0gpPXpKcAWVpp98vXFHmuIdVcGVSt8g=,iv:D7rNkyXckrO6QGpXAdK2nRSL0Dqlk9k+f+Fyd7eON78=,tag:AkjShdvEBGLknUc+aWmxXQ==,type:str]
kind: Secret
metadata:
    name: renovate-env-variable
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPc25KV3poeTVIMVBFOVdq
            bVF0dHFIUHFKNzhWc2pZM3BvaldYNjdUSEZnCnBLTFU1cFdXVTJqd3cyeUxUNnRs
            NzNPSlI1VWRkU3pEUm9XTmpvUC9MSXMKLS0tIHlOcW5LRXVxRGlJYStZcWIzREow
            S2ZMRVlOQ2ladGZLZ1V4YzQzbmN0SW8KjoC/Vsq9dyk/NLVrxuodLYR0xjBYVDON
            co+N18wbIkpaffr61h0tvEJiVgspU9uVtjsqgDN9zjx90/Ap9NYltA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(RENOVATE_TOKEN)$
    lastmodified: "2026-08-27T09:03:14Z"
    mac: ENC[AES256_GCM,data:2eYd4PHHR6NNSqUo0jrYuRSEQsNUzWnXv/FkJo2wvMLCyaizcfyBYV43260LcNMIVp5pSkLz97bEZS05PYNELm8CbC2Yr+hnMYFlw22Sx8k7ymH8Qqk8UG0p6qUescJs7wrTDmT7DehjbOB4UEey49qmwuvT3Pjcdl0zssEbuWY=,iv:/wDTM9Gceko+R+QIBvuODE6bL8/5Q2QI4jAsFUtNX0A=,tag:TVaDXeD0r5TSS8acrOCETg==,type:str]
    version: 3.13.3
