apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:0RrVqv53sEOLrFgw2VEtmoLREr6NdFSYV6IfernuD3ZhS3I9iAepXUpenTbDXOONcRbmWDXCZtY=,iv:IS0wbSsS7BJKnY3DP8m1tn7ftP7WJSHPl4bBnW31tqc=,tag:ATbw2nMRyYlZG+qcW48xjg==,type:str]
kind: Secret
metadata:
    name: renovate-secret
    namespace: renovate
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMmhEbXlRL1oyaUVyakZ2
            UEJVSndUTGNGVVFXbjlBWWZZZjlJK1lTNFE0CjV2cW9SRVpMU2orUVlOdW5EWU1Z
            YjBPM0gxVVg1RUhjbTJOOWZjeEE0MzQKLS0tIHczMHo0WVNiM2ttRVd6TU5Pei9j
            cVMrMHllTVZSVnp3MEhHVG91WDFCc3MKq7IM+CvPbKi7dxn3EJxLEgRTLiO07AnE
            h26Z4IfikqBmyHirSUEpWAeDu/HpEiKC5fSb3NxGX4VYiLvfUKfy9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(RENOVATE_TOKEN)$
    lastmodified: "2026-08-27T09:28:39Z"
    mac: ENC[AES256_GCM,data:Qy/t4KG6mCcZkX0yhHuvlc2WMCZeRrM8TVZF9DpsrTCdIafHSoHrb3LcfRDAxJPhAWtXhSNs2546xEHUlFQCE2LIonxND2Eqm2I9aKxx4ndHIVN65Pk3MZme1tXJLRls3TyRJF2su4vgWYgVQChipydXbjpNUN7UiRSHYKTqa6Q=,iv:CaZalBbl/Y5CmTE9CKIeOVbnq+HZweVgIlPKYeeWw2U=,tag:Pabwe2OZ91vOpKWvzLLvgw==,type:str]
    version: 3.13.3
