apiVersion: v1
kind: Secret
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:ttShN7QG5zmMMesqqTjqsAnGEyKuLaqBRAdpMbAFgoQ9hI9wQtJhm9I4zecpCRCTVKr/pusYUsg=,iv:hNjlOwRVrI+4w/nIHcmH3g1Z6rJW/PYsC9vSErHCnoE=,tag:+xcvaOGtKK7guLDGK1nZtw==,type:str]
metadata:
    name: renovate-secret
    namespace: renovate
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvN1k2WFhQZ0dhTk1hY1Qx
            U0JDMks4TFhxTFRVMkJqRCtwdW5rd1N2aFE4CnhNNzdTcVQrVG52L3VLOTFXS1Ja
            SmMyK2ZDa1kvdmZEYThNM0wxd1BKeFUKLS0tIExmTEFlL1o2UDZ4aktRSG40Y3lF
            UGZRNWU5S3BvZW9FSUtOUXl1M3h0SEUKAIk7d+9gCr8/4Ea4LUfQaHZ1PNsMXeCO
            0o7aStDTm+o27Yn3YS2E+s6Zj9mkeR1T9QgiAAo8BfBYn13XAp93Fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(RENOVATE_TOKEN)$
    lastmodified: "2026-08-27T10:17:40Z"
    mac: ENC[AES256_GCM,data:FkJR7MEx0GVZsMtiskI5BcnKku9i4O33swGxJLN+m2htIVKinvqPpSbW/OPNi9E6jrsP1UPhMJ8TS3LkBv0tJn+UWQyMU16lvSteZdy5Qu/kHBe16gfFO/D97GkQG5U+CZ7jtpz3xo4MI4RIl10FY7DrUDQMvCsCaT2gPSdNplc=,iv:sAQbiXEf2Y4aYk6dFyOi0Kv6AfIVmjyU5d/UE683frQ=,tag:3iqtcLShs9jY7WsoFiw4WA==,type:str]
    version: 3.13.3
