apiVersion: v1
data:
    RENOVATE_KEY: ENC[AES256_GCM,data:AKQFy8fI2xKGzrNfilB/QmVwhGF3H/YNQ8sA1osX5E1qeshq9KxZwq0658aV595eC/e2UvuC/rk=,iv:MhNfk5iQbvhD9CX2Ur+nlLTCVsbPE/SRfgpG0hsH3L0=,tag:1Gkp7ynv2XuzzX4+3kOUKA==,type:str]
kind: Secret
metadata:
    name: renovate-env-variable
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkREREM2NibFhDYTh0eVpR
            RVJ4U2owMERyL2doazkrcnVKc2VWK1ZjUWhZCnI2YjBySmJ5eHBkbmZDWkFzOWQy
            emxiem9DSnhmc1NpeXV1NDlTUkpwSWMKLS0tIEROL1YzalFibmEvMGhDMTRtYXN2
            bi9CR3R1bDlkT1hJUFA3TE4wN2lNYmMKHc2GWb9oiJskwAfY2qt5a8WcWRXZqmeX
            IubM/jAtyThBI/eaWi/HYMVR5OsC0TesgWcCFMBm719yfIfwsYaSNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(RENOVATE_KEY)
    lastmodified: "2026-08-27T08:47:55Z"
    mac: ENC[AES256_GCM,data:k6v2traakP8PAkZe3hDL0qlryQFPUAUmGQWl3DXQV9cHNDKN1ougcoRklzXB6lPQQGJfRDd4OE1e6V3H8VvL2nzOAY8br0lbOGNZbFH9t3n9f/xSh3WU47QFPq4ZtuLs+DHBkasVXdPXe/2DM+K365mQt+EQjIUzSXuQvPIo338=,iv:XyjtTCnVK7lVxn6kQPFACdvicfbnN0xatjJ1cFU6UKs=,tag:uMkU/ORlVJ6pMgQslLKXVg==,type:str]
    version: 3.13.3
