apiVersion: v1
data:
    pat: ENC[AES256_GCM,data:YHuGppRpgpsJJ1uYqhIALTR1gL950LNkChxNNXyMZPz6V3tAAnpQ7El5PGU/BzQeVMXAicqsoHg=,iv:6w+91UXhWEtVfZEqclv/UG3ZinzecbYkBbPLLtRmDC4=,tag:cpwS7BOXH/hAr9s+ZKGf1w==,type:str]
kind: Secret
metadata:
    name: renovate-env-variable
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFanVhYnk0SUc3WVcrQ0Yx
            ZzhzdllQWHA5Y25DQnRjWDdjZUdwOEZhd2lJCmg2a0gvdXNrVG9NUXZlanlTbjhE
            eVhzSXloaGhoci92R05FQ0lrTEpFa0kKLS0tIE5FOEpmNmtzQlVFV0hYZnEwdHNh
            RmFiQ3ZTMXFlMVFxNHd3VlpBSG14aVkKrPUM2dwFarUNTBQIXm0eaWodUmzElZnR
            CfNvBNseb6L378NcFYkyNVqLtDQtUUjYmpxxmeXcKL6E7zD3O4IS4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age183ykmjvkndr0mps307aj9c200mrj30ga35cf6wwud53vypvlza8sa2pyu4
    encrypted_regex: ^(pat)$
    lastmodified: "2026-08-27T07:52:44Z"
    mac: ENC[AES256_GCM,data:Wv/podoLtfWT2BOucnTIsk9K87T/yViUN0vNYh1m3p6Z7fAELMUVRAkfahYZlZOtg1DXINDD1e9jv7TOoUQVvHxgigEww1hArvLJ0P8Suu6x0PC5k/jJoa2VSImiGrEDwIdK/BVGy6S1pb9ec6zbXQ2TjtwU5AyGPn9nkOKr+6A=,iv:qu239oMBphcu29fOTJw/XcoJDmHVqpHELcwjUyBBR74=,tag:Oo3QPyAqPJHCJV+sSgiV2Q==,type:str]
    version: 3.13.3
